[project]
name = "edyp-s2-2025-c"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.4",
    "opencv-python>=4.11.0.86",
    "matplotlib",
    "ipykernel>=7.0.1",
]
